#pragma config(Sensor, in4,    poti,           sensorPotentiometer)
#pragma config(Motor,  port1,           arm,           tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port10,          claw,          tmotorVex269_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[claw] = 127;
	sleep(600);
	motor[claw] = 15;
	sleep(1000);
	while (true)
	{
		motor[arm] = 127;
		unsigned long time = nPgmTime;
		while (SensorValue[poti] < 2350) sleep(10);
		writeDebugStreamLine("%d", nPgmTime - time);
		motor[arm] = 10;
		sleep(200);
		motor[arm] = -127;
		time = nPgmTime;
		while (SensorValue[poti] > 400) sleep(10);
		writeDebugStreamLine("%d", nPgmTime - time);
		motor[arm] = -12;
		sleep(200);
	}
}
