#pragma config(Sensor, in5,    poti,           sensorPotentiometer)
#pragma config(Motor,  port5,           mtr,           tmotorVex393HighSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	SensorValue[poti];
	unsigned long time, diff;
	clearDebugStream();
	while (true)
	{
		while (!vexRT[Btn8R]) sleep(10);
		time = nPgmTime;
		motor[mtr] = 127;
		while (SensorValue[poti] < 3200) sleep(10);
		motor[mtr] = 10;
		diff = nPgmTime - time;
		writeDebugStreamLine("Up:   %d.%d s", diff / 1000, diff % 1000);
		while (vexRT[Btn8R]) sleep(10);

		while (!vexRT[Btn8R]) sleep(10);
		 time = nPgmTime;
		motor[mtr] = -127;
		while (SensorValue[poti] > 550) sleep(10);
		motor[mtr] = -10;
		diff = nPgmTime - time;
		writeDebugStreamLine("Down: %d.%d s", diff / 1000, diff % 1000);
		while (vexRT[Btn8R]) sleep(10);
	}
}
