#pragma config(Sensor, in4,    poti,           sensorPotentiometer)
#pragma config(Sensor, dgtl9,  limArm,         sensorTouch)
#pragma config(Motor,  port5,           mtr,           tmotorVex393HighSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define RL_ARM_TOP 2880
#define ARM_TOP (RL_ARM_TOP - 100)

task main()
{
	SensorValue[poti];
	unsigned long time, diff;
	clearDebugStream();
	while (true)
	{
		while (!vexRT[Btn8R]) sleep(10);
		time = nPgmTime;
		motor[mtr] = 127;
		while (SensorValue[poti] < ARM_TOP) sleep(10);
		motor[mtr] = 10;
		diff = nPgmTime - time;
		writeDebugStreamLine("Up:   %d.%d s", diff / 1000, diff % 1000);
		while (vexRT[Btn8R]) sleep(10);

		while (!vexRT[Btn8R]) sleep(10);
		 time = nPgmTime;
		motor[mtr] = -127;
		while (!SensorValue[limArm]) sleep(10);
		motor[mtr] = -10;
		diff = nPgmTime - time;
		writeDebugStreamLine("Down: %d.%d s", diff / 1000, diff % 1000);
		while (vexRT[Btn8R]) sleep(10);
	}
}
