#pragma config(Motor,  port2,           mtr,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
		if (vexRT[btn7U])
		{
			motor[mtr] = 127;
		}
		else if (vexRT[btn7D])
		{
			motor[mtr] = -127;
		}
		else
		{
			motor[mtr] = 0;
		}
		sleep(50);
	}

}
