#pragma config(Sensor, dgtl1,  enc1,           sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  enc2,           sensorQuadEncoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
		clearLCDLine(0);
		displayLCDNumber(0, 0, SensorValue[enc1]);
		displayLCDNumber(0, 8, SensorValue[enc2]);

		if (nLCDButtons)
		{
			SensorValue[enc1] = 0;
			SensorValue[enc2] = 0;
		}

		sleep(10);
	}
}
