#pragma config(Sensor, in4,    poti,           sensorPotentiometer)
#pragma config(Motor,  port2,           left,          tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           right,         tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	SensorValue[poti];
	unsigned long time, diff;
	clearDebugStream();
	while (true)
	{
		while (!vexRT[Btn8R]) sleep(10);
		time = nPgmTime;
		motor[left] = motor[right] = 127;
		while (SensorValue[poti] < 3100) sleep(10);
		motor[left] = motor[right] = 10;
		diff = nPgmTime - time;
		writeDebugStreamLine("Up:   %d.%d s", diff / 1000, diff % 1000);
		while (vexRT[Btn8R]) sleep(10);

		while (!vexRT[Btn8R]) sleep(10);
		 time = nPgmTime;
		motor[left] = motor[right] = -127;
		while (SensorValue[poti] > 1000) sleep(10);
		motor[left] = motor[right] = -10;
		diff = nPgmTime - time;
		writeDebugStreamLine("Down: %d.%d s", diff / 1000, diff % 1000);
		while (vexRT[Btn8R]) sleep(10);
	}
}
