#pragma config(Sensor, in2,    mobilePoti,     sensorPotentiometer)
#pragma config(Sensor, dgtl1,  limBottom,      sensorTouch)
#pragma config(Sensor, dgtl2,  limTop,         sensorTouch)
#pragma config(Motor,  port2,           liftL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           mobileL,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           driveL1,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           driveL2,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           driveR1,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           driveR2,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           mobileR,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           liftR,         tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define LIFT_HOLD 5

#define RISING(btn) (gJoyCur[btn] && !gJoyLst[btn])
#define FALLING(btn) (!gJoyCur[btn] && gJoyLst[btn])

short gJoyCur[kNumbOfVexRFIndices], gJoyLst[kNumbOfVexRFIndices];
word gMotor[kNumbOfTotalMotors];
short gSensor[kNumbOfTotalSensors];

void updateJoyVals();
void updateMotors();
void updateSensors();
void setLift(byte power);
void setDrive(byte left, byte right);

void updateJoyVals()
{
	memcpy(gJoyLst, gJoyCur, sizeof(gJoyLst));
	for (TVexJoysticks i = (TVexJoysticks)0; i < kNumbOfVexRFIndices; ++i) gJoyCur[i] = vexRT[i];
}

void updateMotors()
{
	for (unsigned int i = 0; i < kNumbOfTotalMotors; ++i) motor[i] = gMotor[i];
}

void updateSensors()
{
	for (unsigned int i = 0; i < kNumbOfTotalSensors; ++i) gSensor[i] = SensorValue[i];
}

void setLift(byte power)
{
	gMotor[liftL] = gMotor[liftR] = power;
}

void setDrive(byte left, byte right)
{
	gMotor[driveL1] = gMotor[driveL2] = left;
	gMotor[driveR1] = gMotor[driveR2] = right;
}

void setMobile(byte power)
{
	gMotor[mobileL] = gMotor[mobileR] = power;
}

task main()
{
	while (true)
	{
		updateJoyVals();
		updateSensors();

		// Handle Lift //
		if (RISING(Btn5U)) setLift(127);
		else if (FALLING(Btn5U) && gMotor[liftL] == 127) setLift(LIFT_HOLD);

		if (RISING(Btn5D)) setLift(-127);
		else if (FALLING(Btn5D) && gMotor[liftL] == -127) setLift(LIFT_HOLD);

		if (gMotor[liftL] > LIFT_HOLD && gSensor[limTop]) setLift(LIFT_HOLD);
		else if (gMotor[liftL] < 0 && gSensor[limBottom]) setLift(0);

		// Handle Drive //
		short x = gJoyCur[Ch4];
		short y = gJoyCur[Ch3];
		if (abs(x) < 10) x = 0;
		if (abs(y) < 10) y = 0;
		short left = y + x;
		short right = y - x;
		if (abs(left) > 127) left = 127 * sgn(left);
		if (abs(right) > 127) right = 127 * sgn(right);
		setDrive(left, right);

		// Handle Mobile //
		if (RISING(Btn6U)) setMobile(127);
		if (RISING(Btn6D)) setMobile(-127);

		if (gSensor[mobilePoti] < 440 && gMotor[mobileL] < -15) setMobile(-15);
		if (gSensor[mobilePoti] > 2500 && gMotor[mobileL] > 15) setMobile(15);

		updateMotors();
		sleep(10);
	}
}
