#pragma config(Sensor, in2,    poti,           sensorPotentiometer)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	clearDebugStream();
	while (true)
	{
		writeDebugStreamLine("%d,%d", nPgmTime, SensorValue[poti]);
		sleep(10);
	}
}
