#pragma config(Sensor, in1,    shifterPoti,    sensorPotentiometer)
#pragma config(Motor,  port2,           shifter,       tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool TimedOut(unsigned long timeOut, const string description)
{
	if (nPgmTime > timeOut)
	{
		stopAllTasks();
		return true;
	}
	else
		return false;
}

#define TASK_POOL_SIZE 19

#include "../src/utilities.h"
#include "../src/motors.h"
#include "../src/sensors.h"
#include "../src/pid.h"
#include "../src/task.h"
#include "../src/notify.h"
#include "../src/async.h"
#include "../src/state.h"
#include "../src/cycle.h"

#include "../src/utilities.c"
#include "../src/motors.c"
#include "../src/sensors.c"
#include "../src/pid.c"
#include "../src/task.c"
#include "../src/notify.c"
#include "../src/async.c"
#include "../src/state.c"
#include "../src/cycle.c"

#define SHIFTER_BRAKES 80
#define SHIFTER_MIDDLE 1900
#define SHIFTER_HIGH 4000

sPID pid;

typedef enum _tShifterStates
{
	shifterBrakes,
	shifterMiddle,
	shifterHigh
} tShifterStates;

MAKE_MACHINE(shifter, tShifterStates, shifterMiddle,
{
case shifterBrakes:
	gMotor[shifter].power = -127;
	while (gSensor[shifterPoti].value > SHIFTER_BRAKES) sleep(10);
	gMotor[shifter].power = -10;
	break;
case shifterMiddle:
	pidReset(pid);
	sCycleData cycle;
	initCycle(cycle, 10, "PID");
	while (true)
	{
		pidCalculate(pid, SHIFTER_MIDDLE, (float) gSensor[shifterPoti].value);
		gMotor[shifter].power = pid.output;
		endCycle(cycle);
	}
case shifterHigh:
	gMotor[shifter].power = 127;
	while (gSensor[shifterPoti].value < SHIFTER_HIGH) sleep(10);
	gMotor[shifter].power = 10;
	break;
})

task main()
{
	bool lastBrakes = false;
	bool lastMiddle = false;
	bool lastHigh = false;

	pidInit(pid, 0.07, 0, 0.2, -1, -1, 10, 127);

	setupMotors();
	setupSensors();
	tInit();

	shifterSetup();

	displayLCDString(1, 0, "P      LO     HI");

	sCycleData cycle;
	initCycle(cycle, 10, "main");
	while (true)
	{
		bool brakes = nLCDButtons & 0b001;
		bool middle = nLCDButtons & 0b010;
		bool high = nLCDButtons & 0b100;

		updateSensorInputs();

		if (brakes && !lastBrakes)
			shifterSet(shifterBrakes);
		if (middle && !lastMiddle)
			shifterSet(shifterMiddle);
		if (high && !lastHigh)
			shifterSet(shifterHigh);

		lastBrakes = brakes;
		lastMiddle = middle;
		lastHigh = high;

		updateMotors();

		endCycle(cycle);
	}
}

ASYNC_ROUTINES
(
USE_ASYNC(shifterInternal)
)
