#pragma config(Sensor, in6,    shifterPoti,    sensorPotentiometer)
#pragma config(Motor,  port10,          shifter,       tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../src/utilities.h"
#include "../src/motors.h"
#include "../src/sensors.h"
#include "../src/pid.h"

#include "../src/utilities.c"
#include "../src/motors.c"
#include "../src/sensors.c"
#include "../src/pid.c"

#define SHIFTER_BRAKES 80
#define SHIFTER_MIDDLE 1800
#define SHIFTER_HIGH 4000

typedef enum _tShifterStates
{
	shifterBrakes,
	shifterMiddle,
	shifterHigh
} tShifterStates;

task main()
{
	bool lastBrakes = false;
	bool lastMiddle = false;
	bool lastHigh = false;

	tShifterStates state = shifterMiddle;

	sPID pid;

	pidInit(pid, 0.07, 0, 0.12, -1, -1, -1, 127);

	setupMotors();
	setupSensors();

	displayLCDString(1, 0, "P      LO     HI");

	while (true)
	{
		bool brakes = nLCDButtons & 0b001;
		bool middle = nLCDButtons & 0b010;
		bool high = nLCDButtons & 0b100;

		updateSensorInputs();

		if (brakes && !lastBrakes)
			state = shifterBrakes;
		if (middle && !lastMiddle)
		{
			state = shifterMiddle;
			pidReset(pid);
		}
		if (high && !lastHigh)
			state = shifterHigh;

		lastBrakes = brakes;
		lastMiddle = middle;
		lastHigh = high;

		int value = gSensor[shifterPoti].value;

		switch (state)
		{
			case shifterBrakes:
				gMotor[shifter].power = value > SHIFTER_BRAKES ? -127 : -10;
				break;
			case shifterMiddle:
				pidCalculate(pid, SHIFTER_MIDDLE, (float) value);
				gMotor[shifter].power = fabs(pid.error) > 100 ? pid.output : 0;
				break;
			case shifterHigh:
				gMotor[shifter].power = value < SHIFTER_HIGH ? 127 : 10;
				break;
		}

		updateMotors();

		sleep(10);
	}
}
