#pragma config(Sensor, dgtl11, frontSonic,     sensorSONAR_mm)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
		if (SensorValue[frontSonic] != -1 && SensorValue[frontSonic] < 195) playImmediateTone(1000, 1);
		else sleep(10);
	}
}
