#pragma config(Sensor, dgtl11, sonic,     sensorSONAR_mm)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
		writeDebugStreamLine("%d,%d", nPgmTime, SensorValue[sonic]);
		sleep(10);
	}
}
