from sys import argv

max = int(argv[1])

for i in range(max + 1):
    print('#define NEW_ASYNC_VOID_%d(%s) \\' % (i, ', '.join(['func', *('type%d' % j for j in range(i))])))
    print('byte func##Dummy; \\')
    print('typedef struct _asyncData_##func { \\')
    if i > 0:
        for j in range(i):
            print('  type%d arg%d; \\' % (j, j))
    else:
        print('  int _dummy[0]; \\')
    print('} sAsyncData_##func; \\')
    print('void _asyncTask_##func(sAsyncData_##func *data, sNotifier *notifier) { \\')
    # print('  writeDebugStreamLine("Instance of " #func " started"); \\')
    print('  sAsyncData_##func _data; \\')
    print('  memcpy(&_data, data, sizeof(sAsyncData_##func)); \\')
    print('  notify(*notifier); \\')
    print('  func(%s); \\' % ', '.join('_data.arg%d' % j for j in range(i)))
    print('} \\')
    print('unsigned long func##Async(%s) { \\' % ', '.join('type%d arg%d' % (j, j) for j in range(i)))
    # print('  writeDebugStreamLine("Starting instance of " #func); \\')
    print('  sAsyncData_##func data; \\')
    for j in range(i):
        print('  data.arg%d = arg%d; \\' % (j, j))
    print('  return _startAsync(&func##Dummy, &data); \\')
    print('} \\')
    print('bool func##Kill() { \\')
    # print('  writeDebugStreamLine("Killing all instances of " #func); \\')
    print('  for (int i = 0; i < TASK_POOL_SIZE; ++i) \\')
    print('    if (gAsyncTaskData[i].id == &func##Dummy && tEls[threadPoolTask0 + i].parent != -1) { \\')
    print('      _killAsync(i); \\')
    print('      return true; \\')
    print('    } \\')
    print('  return false; \\')
    print('}')
    print()

print('#define USE_ASYNC(func) \\')
print('if (data->id == &func##Dummy) { \\')
print('  _asyncTask_##func((sAsyncData_##func *)data->data, &data->notifier); \\')
print('  notify(data->notifier); \\')
print('  return true; \\')
print('}')
print()

print('#define ASYNC_ROUTINES(content) \\')
print('bool _runAsync(sAsyncTaskData *data) { \\')
# print('  writeDebugStreamLine("Starting asynchronous function on threadPoolTask%d", nCurrentTask - threadPoolTask0); \\')
print('  content \\')
print('  return false; \\')
print('}')
print()

print('typedef struct _sAsyncTaskData {')
print('  byte *id;')
print('  void *data;')
print('  unsigned long unique;')
print('  sNotifier notifier;')
print('} sAsyncTaskData;')
print()

print('sAsyncTaskData gAsyncTaskData[TASK_POOL_SIZE];')
print('unsigned long _asyncUnique = 1;')
print()

print('void asyncInit();')
print('void await(unsigned long unique, unsigned long timeout, const string description);')
print('void kill(unsigned long unique);')
print('void _awaitAsync(byte index, unsigned long timeout, const string description);')
print('void _killAsync(byte index);')
print('bool _runAsync(sAsyncTaskData *data);')
print('unsigned long _startAsync(byte *id, void *data);')
print()

for i in range(20):
    print('#if TASK_POOL_SIZE > %d' % i)
    print('task threadPoolTask%d() {' % i)
    print('  if (!_runAsync(&gAsyncTaskData[%d]))' % i)
    print('    writeDebugStreamLine("ASYNC %d");' % i)
    print('  return_t;')
    print('}')
    print('#endif')
    print()
