#pragma config(Sensor, in1,    leftLight,      sensorReflection)
#pragma config(Sensor, in2,    midLight,       sensorReflection)
#pragma config(Sensor, in3,    rightLight,     sensorReflection)
#pragma config(Sensor, in4,    wristPoti,      sensorPotentiometer)
#pragma config(Sensor, in6,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  rightEnc,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEnc,        sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  scissorEnc,     sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  Sonar,          sensorSONAR_cm)
#pragma config(Motor,  port1,           frontRight,    tmotorVex393TurboSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           backRight,     tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           frontLeft,     tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           backLeft,      tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           claw,          tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           scissorLeft,   tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           scissorRight,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          wrist,         tmotorVex393TurboSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Includes
#include "task.h"
#include "async.h"
#include "motors.h"
#include "sensors.h"
#include "joysticks.h"
#include "cycle.h"
#include "utilities.h"
#include "pid.h"
#include "notify.h"
#include "task.c"
#include "async.c"
#include "motors.c"
#include "sensors.c"
#include "joysticks.c"
#include "cycle.c"
#include "utilities.c"
#include "pid.c"
#include "notify.c"
#include "controls.h"
/////

int lightVal;
int lightThresh;
int lightMin = 2000;
int lightMax = 0;
int scissorBottom = -180;
int scissorTop = 1400;

/////////////////// cycle test. delete after

void setDrive (int left, int right)
{
	motor [frontRight] = motor [backRight] = right;
	motor [frontLeft] = motor [backLeft] = left;
}

void setArm (int speed, int distance)
{
	motor [scissorLeft] = motor [scissorRight] = speed;
	if (speed > 0)
	{
		while (SensorValue [scissorEnc] < distance) sleep(10);
	}
	else if (speed < 0)
	{
		while (SensorValue [scissorEnc] < distance) sleep(10);
	}

}

void closeClaw (bool state)
{
	if (state == true) motor [claw] = 127;
	else if (state == false) motor [claw] = -127;
	unsigned long startTimer = nPgmTime;
	while (nPgmTime-startTimer < 200) sleep (10);
	motor [claw] = 0;
}

void calibrate ()
{
	sCycleData cycle;
	initCycle(cycle, 10, "calibrate");

	setDrive (127, 127);
	while (SensorValue[leftEnc] < 700)
	{
		lightVal = SensorValue[midLight];
		if (lightVal < lightMin) lightMin = lightVal;
		if (lightVal > lightMax) lightMax = lightVal;
	}
	lightThresh = (lightMax + lightMin) / 2;
	setDrive (0, 0);

	endCycle(cycle);
} // if sensorVal<1000, should be a white line

task main()
{
	clearDebugStream();
	moveToTarget(
	writeDebugStream ("%d", nPgmTime);
}
